// Flat ESLint config. `eslint-config-expo/flat` carries the Expo/React Native +
// TypeScript rules; `eslint-config-prettier` (last) disables stylistic rules
// that would fight Prettier — formatting is Prettier's job, correctness is ESLint's.
const expoConfig = require('eslint-config-expo/flat');
const eslintConfigPrettier = require('eslint-config-prettier');

module.exports = [
  ...expoConfig,
  eslintConfigPrettier,
  {
    ignores: [
      'node_modules/*',
      '.expo/*',
      'dist/*',
      // Generated by drizzle-kit — not hand-edited.
      'src/core/db/migrations/*',
    ],
  },
];
